export default {
    profileSettings: "Profile Settings",
    profileSubtitle: "View and manage your personal and professional details.",
    loadingProfile: "Loading profile...",
    personalInformation: "Personal Information",
    fullName: "Full Name",
    email: "Email",
    industry: "Industry",
    editProfile: "Edit Profile",
    languagePreferences: "Language Preferences",
    english: "English",
    arabic: "Arabic",
    dashboardTitle: "Skillyfy Dashboard",
    welcomeBack: "Welcome Back",
    welcomeSubtitle: "explore your assessments and personalized learning path.",
    loadingProfile: "Loading your profile...",
    quickActions: "Quick Actions",
    selfAssessment: "Self Assessment",
    selfAssessmentDescription: "Evaluate your own skills and progress.",
    allUsersResults: "All Users Results",
    allUsersResultsDescription: "View overall user performance and analytics.",
    pastAssessments: "Past Assessments",
    pastAssessmentsDescription: "Review your previous assessments and history.",
    processingRequest: "Processing your request...",
    logout: "Logout",
    loginAgain: "No user email found. Please login again.",
    completeProfileWarning: "Please complete your profile before taking assessments.",
    noPastAssessments: "No past assessments found.",
    noAssessmentsFound: "No assessments found.",
    footerText: "Empowering your learning journey.",
    helloSkillyfy: "Hello Skillyfy! 👋",
    loginLeftSubtitle: "Skip repetitive manual tasks. Be highly productive through automation and save tons of time!",
    allRightsReserved: "All rights reserved.",
    welcomeBack: "Welcome Back!",
    dontHaveAccount: "Don’t have an account?",
    createAccount: "Create a new account now",
    itsFree: "it's free!",
    email: "Email",
    enterEmail: "Enter your email",
    password: "Password",
    enterPassword: "Enter your password",
    loggingIn: "Logging in...",
    loginNow: "Login Now",
    loginWithGoogle: "Login with Google",
    forgotPassword: "Forgot password?",
    clickHere: "Click here",
    loadingAssessments: "Loading assessments...",
    retry: "Retry",
    noAssessmentsFound: "No assessments found.",
    allUsersAssessments: "All Users Assessments",
    backToDashboard: "Back to Dashboard",
    unknownUser: "Unknown User",
    noRole: "No role",
    noAssessmentData: "No assessment data found.",
    backToDashboard: "Back to Dashboard",
    performanceExcellent: "Excellent",
    performanceGood: "Good",
    performanceAverage: "Average",
    performanceNeedsImprovement: "Needs Improvement",
    yourScore: "Your Score",
    assessmentDetails: "Assessment Details",
    back: "Back",
    technicalQuestions: "Technical Questions",
    noTechnicalQuestions: "No technical questions available.",
    question: "Q",
    type: "Type",
    yourAnswer: "Your Answer",
    correctAnswer: "Correct Answer",
    notAnswered: "Not answered",
    notAvailable: "N/A",
    learningRoadmap: "Learning Roadmap",
    copy: "Copy",
    noRoadmap: "No roadmap available",
    roadmapCopied: "📋 Roadmap copied to clipboard!",
    learn: "Learn",
    selfAssessment: "Self Assessment",
    answerCarefully: "Answer each question carefully to receive personalized insights.",
    totalQuestions: "Total Questions",
    domain: "Domain",
    level: "Level",
    type: "Type",
    typeYourAnswer: "Type your answer...",
    submitting: "Submitting",
    submitAssessment: "Submit Assessment",
    noQuestionsAvailable: "No questions available. Please regenerate assessment.",
    noAssessmentDataFound: "No assessment data found. Please try again.",
    evaluatingAnswers: "Evaluating your answers",
    invalidAssessmentData: "Invalid assessment data. Please retry.",
    evaluationFailed: "Failed to evaluate responses.",
    noResultData: "No result data found. Please complete an assessment first.",
    assessmentResults: "Assessment Results",
    back: "Back",
    overallSummary: "Overall Summary",
    score: "Score",
    totalQuestions: "Total Questions",
    percentage: "Percentage",
    strengths: "Strengths",
    notAvailable: "N/A",
    careerPathRecommendations: "Career Path Recommendations",
    requirements: "Requirements",
    salary: "Salary",
    recommendedLearningPath: "Recommended Learning Path",
    priority: "Priority",
    timeline: "Timeline",
    resources: "Resources",
    studyRoadmap30: "30-Day Study Roadmap",
    completeYourProfile: "Complete Your Profile",
    fullName: "Full Name",
    email: "Email",
    currentRole: "Current Role",
    yearsOfExperience: "Years of Experience",
    education: "Education",
    industry: "Industry",
    keySkills: "Key Skills (comma separated)",
    careerGoals: "Career Goals",
    saveProfile: "Save Profile",
    saving: "Saving...",
    profileUpdated: "Profile updated successfully!",
    profileSaveFailed: "Failed to save profile. Try again.",
    somethingWentWrong: "Something went wrong. Please try again.",
    editYourProfile: "Edit Your Profile",
    updatePersonalDetails: "Update your personal details and professional background.",
    fullName: "Full Name",
    currentRole: "Current Role",
    yearsOfExperience: "Years of Experience",
    education: "Education",
    industry: "Industry",
    keySkills: "Key Skills",
    careerGoals: "Career Goals",
    cancel: "Cancel",
    saveChanges: "Save Changes",
    profileUpdated: "Profile updated successfully!",
    updateFailed: "Update failed.",
    generatingLearningContent: "Generating detailed learning content...",
    goBack: "Go Back",
    noContentAvailable: "No content available. Please try again.",
    back: "Back",
    learningContent: "Learning Content",
    practice: "Practice",
    selectPageToViewContent: "Select a page to view its learning materials",
    loadingAssessments: "Loading assessments...",
    errorOccurred: "Oops! Something went wrong",
    goBack: "Go Back",
    justNow: "Just now",
    minutesAgo: "{{count}} min ago",
    hoursAgo: "{{count}} hr ago",
    daysAgo: "{{count}} days ago",
    noAssessments: "No Assessments Yet",
    takeFirstAssessment: "Take your first assessment to see your progress here.",
    pastAssessments: "Past Assessments",
    back: "Back",
    assessmentNumber: "Assessment #{{num}}",
    score: "Score",
    percentage: "Percentage",
    status: "Status",
    completed: "Completed",
    in_progress: "In Progress",
    failed: "Failed",
};
